# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        build:
            context: ./vendor/laravel/sail/runtimes/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
                APP_ENV: '${APP_ENV}'
        image: sail-8.0/site-app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        image: 'mysql:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'site-volume:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
          retries: 3
          timeout: 5s

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_ARBITRARY: 1
        ports:
            - '${PHPMYADMIN_PORT:-8088}:80'
        depends_on:
            - mysql
        networks:
            - sail
networks:
    sail:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.0.0.0/24
                # - gateway: 10.0.0.1
volumes:
    site-volume:
        driver: local
